name: asiah_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  json_annotation: ^4.8.0
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  json_serializable: ^6.3.1
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  google_fonts: ^4.0.3
  smooth_page_indicator: ^1.0.1
  get_storage: ^2.1.1
  lottie: ^2.3.2
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/lottie/
  uses-material-design: true

